### ISSUE TITLE
HubSpot adds __hstc, __hssc and __hsfp query params to all external URL, making them invalid

### ISSUE THREAD

**Issue by lolmaus** [segment-integrations/analytics.js-integration-hubspot#7]
Hi!

Here's a string I'm applying to a `href` attribute of a link:

    https://example.com/app#/tree?path=foo.bar

But when its rendered on the page, here's how it ends up looking:
    https://example.com/app&__hstc=181257784.ec3b8f50ceac6ae94ada7d99c135638e.1456488482298.1458396994219.1458561178659.71&__hssc=181257784.16.1458561178659&__hsfp=3702051802#/tree?path=foo.bar

Our backend filters results by query params at this point, so the URL does not yield what it's supposed to.

How do I prevent those `__hstc`, `__hssc` and `__hsfp` query qarams from polluting all URLs? Note that I'm unable to prevent them from appearing at the frontend logic level, because at that level URLs are clean and get polluted after rendering by the HubSpot script injected by `segmentio/analytics.js`.

**Comment by lolmaus** [comment]
Moved from https://github.com/segmentio/analytics.js/issues/504#issuecomment-216990561 by @hankim813's request.

**Comment by hankim813** [comment]
@lolmaus thanks for moving this here.

Can you link me to your public site that has this behavior? I'm not able to reproduce this behavior on my test site when I have hubspot enabled. Are you also using Segment hosted CDN for analytics.js or your own hosted version?

**Comment by lolmaus** [comment]
@hankim813 We have resolved the issue following advice from [this thread](https://wordpress.org/support/topic/hubspot-plugin-passing-url-parameters).

>> We have a hardcoded link (...) appended with parameters like the following:
>> 
>>     ?__hstc=189055220.0fe00ed76ba418b73b715b36b16c0216.1349720370113.1349720370113.1349967945400.2&__hssc=189055220.1.1349967945400
>
> you can remove that parameter by going into your HubSpot settings (in HubSpot, not WordPress), going to "Tracking and Privacy," and turning off "Automatic Cross-Domain Link-Tracking"

This problem was kinda mystic. It didn't happen to everybody and couldn't be reproduced reliably.

**Comment by hankim813** [comment]
Ahh interesting. Good to know for future reference though. Thanks for the update!
